### Required by all modules
data_name: 5k_pbmc_v3  # the python code to find this: fastq_link.split("/")[-2] OR filtered_feature_bc_matrix_link.split("/")[-2]
seed_list: []
frac_list: []
count_matrix_generation_method: "cellranger"  # "kb" or "cellranger" or "both"; only used by main.py
kb_version: 0.28.2  # "" for agnostic
cellranger_version: 7.2.0  # "" for agnostic
### Required by all modules


### Required by kb/cellranger count
kb_sequencing_technology: "10xv3"  # find on 10x website
kb_count_format: "mtx" # mtx for matrix only, h5ad for matrix + h5ad
kb_workflow: "nac"  # kb only: nac for unspliced + spliced (in addition to spliced only) (kb 28+ only), standard for spliced only
reference_selector: "most_recent"  # specific date (yymm) or "most_recent"


### Optional (as needed)
fastq_link: "https://cg.10xgenomics.com/samples/cell-exp/3.0.2/5k_pbmc_v3/5k_pbmc_v3_fastqs.tar"  # find on 10x website

filtered_feature_bc_matrix_link: "https://cf.10xgenomics.com/samples/cell-exp/4.0.0/SC3_v3_NextGem_SI_PBMC_10K/SC3_v3_NextGem_SI_PBMC_10K_filtered_feature_bc_matrix.tar.gz"  # find on 10x website

cellranger_package_link: "https://cf.10xgenomics.com/releases/cell-exp/cellranger-7.2.0.tar.gz?Expires=1705989023&Key-Pair-Id=APKAI7S6A5RYOXBWRPDA&Signature=lMN74QKGVwrRhzyjGjZDh0F9oSYZ0YzRnisPtEkMoIGwMs1k9CPObqGkOh43F3o-mcaQ4k~LfJ79rK5rBY2GFbeOGEK4IIUN3sfN7fX6VL5n140TKf~W9aPjTslhA8VTJCNgpLGdMa~K9GdEAETwCOHtMd-Z5L3P9czdfs~p~zu883Ofvs6gjeFVKnqvEDv960Y278q8gJeUw4HHb42qS~WaVtkDPf3Y6XfDrv0uUy5tEqbRRUFA7YTbi4PfEFXLQ25LePdqRfUoiM7IYl0Y5nnnZA~omFGck4fGxr7blg6-zd8idF3CSF5civJP-zhgqHVNfXlxfz66DYU41flGoA__"   # find here: https://www.10xgenomics.com/support/software/cell-ranger/downloads/previous-versions

cellranger_transcriptome_link: "https://cf.10xgenomics.com/supp/cell-exp/refdata-gex-GRCh38-2020-A.tar.gz"

ensembl_release: 110  # for kb ref; not required if reference_selector == "most_recent"



